name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # আপনার প্রজেক্ট অনুযায়ী দিন

      - name: Install dependencies
        working-directory: ./YOUR_FLUTTER_PROJECT_FOLDER
        run: flutter pub get

      - name: Build APK
        working-directory: ./YOUR_FLUTTER_PROJECT_FOLDER
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: YOUR_FLUTTER_PROJECT_FOLDER/build/app/outputs/flutter-apk/app-release.apk
